# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'Bitaqaty-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

# Pods for Bitaqaty-iOS
pod 'Alamofire'
pod 'XLPagerTabStrip'
pod 'AlamofireImage'
pod 'IQKeyboardManagerSwift'
pod 'SwiftKeychainWrapper'
pod 'Charts'
pod 'JTAppleCalendar'
pod 'lottie-ios'
pod 'Endless'
pod 'LiveChat', '~> 2.0.24'
pod 'Kingfisher'

end
